// flow-typed signature: d07fa982072aacc074569d426ca7365b
// flow-typed version: <<STUB>>/es6-class-mixin_v^1.0.5/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-class-mixin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-class-mixin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-class-mixin/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-class-mixin/test/index.js' {
  declare module.exports: $Exports<'es6-class-mixin/test/index'>;
}
